### ISSUE TITLE
Big Visual Bug

### ISSUE THREAD

**Issue by Uniqeues** [Pandarix/Beautify#5] opened 2022-08-26 20:53 UTC
Hi! This mod Beautify version v.1.4.0 is causing this visual bug. Im playing on latest release of forge on 1.19.  What should i do?
When i uninstall this mod everything works perfectly fine.

![2022-08-26_22 50 48](https://user-images.githubusercontent.com/101985113/186988871-141a3017-454a-4156-a32a-14259698bd41.png)

**Comment by Pandarix** [comment] 2022-08-26 21:06
Hi,
could you elaborate on that problem? I can't seem to see what you're trying to point out.
Your screenshot looks like slightly modded terrain, but Beautify doesn't modify any terrain.
Otherwise, there's nothing on that screenshot I could figure out ^^'.

**Comment by Uniqeues** [comment] 2022-08-26 21:09
I meant that picture overall the backround looks like 144p resolution. Yes
game is slightly modded. This visual bug where everything in background
looks like 144p video always dissapear when i delete Beautify.

**Comment by Pandarix** [comment] 2022-08-26 21:42
Well, I can't say for certain that it's not a problem of my mod.
What other mods are installed and do you have Mipmaps on?
Turning them off and on again seems to do the trick for some people. I'll try to further look into this.

**Comment by Uniqeues** [comment] 2022-08-26 21:48
Yes i have mipmap levels on. I tried antialiasing with optifine it worked
little bit. It just make the 144p resolution effect move a bit further but
it was still there and i found it a bit annoying. Tommorow i will try
launching only optifine and beautify to see if there is some
incompatibility with other mods.

**Comment by Pandarix** [comment] 2022-08-26 21:51
Alrighty, sorry for the inconvenience tho.
Keep me posted :) I hope it's not an incompatibility issue :[.
I've run my Mod with a few mods for testing purposes, but didn't come across anything sus.
It seems to work with [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) for me. I haven't tried Optifine yet.
My bad

**Comment by Uniqeues** [comment] 2022-08-27 07:32
Soo right now i have launched minecraft with optifine and beautify only. The results are same as yesterday. The background looks still like 144p video. Then i tried to relaunch the game only with beautify and it worked. There was no issue with that background anymore. Then i tried to launch the game only with optifine and it still worked. There was no issue. I've used same settings every time i tested it. So it happens only when i launch my game with optifine and beautify. 

Only Optifine
![2022-08-27_09 31 02](https://user-images.githubusercontent.com/101985113/187020100-68b4f7a5-b232-4f75-ac04-cf560508e018.png)

Only Beautify
![2022-08-27_09 27 55](https://user-images.githubusercontent.com/101985113/187020040-6b940a2d-1203-4cc4-bfd2-69823e141a2d.png)

Beautify with Optifine
![image](https://user-images.githubusercontent.com/101985113/187019873-ce7c3b7a-3c66-4832-9201-27a82d9efb0e.png)

Installed Mods
![2022-08-27_09 21 56](https://user-images.githubusercontent.com/101985113/187019851-792bc9bb-5561-4935-8383-58ebd77c76af.png)

**Comment by Pandarix** [comment] 2022-08-27 09:11
First of all, thank you for your continuing help on this issue.
I'm continuing on looking through the issue, here's what I found/did so far:

- "Potentially any mod because Optifine is a closed source, highly invasive, non-Forge mod which hacks the entire rendering system that almost all mods use, and Optifine could break anything with any update." [source](https://www.reddit.com/r/feedthebeast/comments/ez5fyl/lets_list_mods_that_conflict_with_optifine/)

- Optifine has been outperformed recently, so regardless of the Issue, I'd recommend using these (which also provides a fix I guess, since I've tested the mod with these):
   -[Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) for Shaders
   -[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) for Performance
   -[FerriteCore](https://www.curseforge.com/minecraft/mc-mods/ferritecore) for Optimization
   
- I'll be testing the mod with Optifine and will be updating the models if needed

- I've asked in modding communities for help, so I'll get some more expertise into this confusing thing (this is my first mod after all ^^')

I'm going to comment again when I've found out something o~o

**Comment by Pandarix** [comment] 2022-08-27 10:03
![Bild_2022-08-27_120251779](https://user-images.githubusercontent.com/98489042/187025387-b6fdc809-2241-4f30-94b1-cecc55d06e44.png)
Well that seems to be the consensus

**Comment by Uniqeues** [comment] 2022-08-27 19:57
That was fast :D I would really like to try rubidium but it doesn't work for 1.19 forge. That's why i've choosed to use optifine. But could you at least try something to fix it if it's possible? Beautify look like pretty good mod.

**Comment by Pandarix** [comment] 2022-08-27 20:13
Really?
Works for me
Try this download: https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3839967

I'll still try to fix it, dw
But that's the fastest solution so far ^^'

**Comment by Uniqeues** [comment] 2022-08-27 20:36
Wow thanks! I've tried to install rubidium but i've only found for 1.18.
Thanks!

**Comment by Uniqeues** [comment] 2022-08-28 10:25
Hey i know this doesn't fit in here but could i ask you something? What is this:
![Screenshot_6](https://user-images.githubusercontent.com/101985113/187069256-364e4f1e-2f53-4944-8bcb-e5655e4c2a4b.png)
Sometimes maybe every 10th block this appears underneath the block. Thank you for help.

**Comment by Pandarix** [comment] 2022-08-28 11:30
Must be some performance tweak of the rendering mods.
Try enabling and disabling performance settings one by one.

If that doesn't work, disable all and restart. When the problem ist fixed, you'll have to repeat that procedure to figure out what settings causes that. Could be something related to a setting called "Fast Math".

**Comment by Pandarix** [comment] 2022-08-28 14:06
Also, you said that you were running Forge on the latest 1.19 Version but you've installed Beautify for the 1.19.2
Always check what Version you are downloading. The one you'd need for 1.19 would be [this one](https://www.curseforge.com/minecraft/mc-mods/beautify-decorate/files/3945386).
Under Files, there are all Downloads with their corresponding Versions like this:
![image](https://user-images.githubusercontent.com/98489042/187077909-d2b74ed0-ba78-4dee-8e42-8decc9f2ff17.png)
Furthermore, I always label my Versions like this for u to check if the download is right: Beautify-[Version of Minecraft]-[Version of Mod]

**Comment by Uniqeues** [comment] 2022-08-28 16:13
But isn't there also label with 1.19? where is 1.19.2 a i think it also
shows 1.19. Or i'm pretty blind.

**Comment by Pandarix** [comment] 2022-08-28 17:52
![Screenshot_20220828-195021_Chrome](https://user-images.githubusercontent.com/98489042/187087832-a6b1d10e-1dba-4dd9-8807-cca37e4540d6.jpg)
In the release you're using the download is marked as 1.19, called  1.19 and the jar is called 1.19
So that shouldn't be the case

**Comment by Pandarix** [comment] 2022-08-28 17:53
If you have any questions left, please ask.
Otherwise, I'll mark this issue as closed for now ;)

**Closed** 2022-09-03 09:26 UTC
Labels: bug
